name: Update Order Data
on:
  repository_dispatch:
    types: [update_order_data]

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Create data directory
        run: mkdir -p data
        
      - name: Update orders.json
        run: |
          echo '${{ toJson(github.event.client_payload.data) }}' > temp_order.json
          
          node -e "
            const fs = require('fs');
            const newOrder = JSON.parse(fs.readFileSync('temp_order.json', 'utf8'));
            
            let orders = { orders: {} };
            if (fs.existsSync('data/orders.json')) {
              orders = JSON.parse(fs.readFileSync('data/orders.json', 'utf8'));
            }
            
            orders.orders[newOrder.recordId] = newOrder;
            
            fs.writeFileSync('data/orders.json', JSON.stringify(orders, null, 2));
            console.log('Updated orders.json with order:', newOrder.orderId);
          "
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/orders.json
          git commit -m "Update order data for recordId ${{ github.event.client_payload.recordId }}" || exit 0
          git push
